manifest:
  version: "0.13"

  defaults:
    remote: zephyrproject

  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: mcuboot
      url-base: https://github.com/mcu-tools
    - name: matter
      url-base: https://github.com/project-chip

  projects:
    - name: zephyr
      revision: v4.4.0-rc1
      west-commands: scripts/west-commands.yml
    - name: cmsis
      revision: 512cc7e895e8491696b61f7ba8066b4a182569b8
      path: modules/hal/cmsis
    - name: cmsis_6
      repo-path: CMSIS_6
      revision: 30a859f44ef8ab4dc8f84b03ed586fd16ccf9d74
      path: modules/hal/cmsis_6
    - name: mbedtls
      revision: 26158d1c012477e77765d138b26a791db917c881
      path: modules/crypto/mbedtls
    - name: tf-psa-crypto
      revision: 6820f1dadc67c289d2dc63aec495519c9d589d8e
      path: modules/crypto/mbedtls/tf-psa-crypto
    - name: openthread
      revision: e4d97681c53ec1cc34af1404ad2960adda4ba691
      path: modules/lib/openthread

    - name: mcuboot
      remote: mcuboot
      revision: cf5810201c84d6e266aeda2abdab80854066ac08
      path: bootloader/mcuboot

    - name: connectedhomeip
      remote: matter
      revision: fdb31dbcb3ebe000ad3e41b386e90849937948f9
      path: connectedhomeip
      import: false

  self:
    path: zephyr-thread-rt58x
    west-commands: scripts/west-commands.yml
