manifest:
  version: "0.13"

  defaults:
    remote: zephyrproject

  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: mcuboot
      url-base: https://github.com/mcu-tools

  projects:
    - name: zephyr
      revision: v4.4.0-rc1
      west-commands: scripts/west-commands.yml
    - name: cmsis
      revision: 512cc7e895e8491696b61f7ba8066b4a182569b8
      path: modules/hal/cmsis
    - name: cmsis_6
      repo-path: CMSIS_6
      revision: 30a859f44ef8ab4dc8f84b03ed586fd16ccf9d74
      path: modules/hal/cmsis_6
    - name: mcuboot
      remote: mcuboot
      revision: v2.1.0
      path: bootloader/mcuboot

  self:
    path: zephyr-thread
