/*
 * RT583 Matter Lighting App — Application task.
 *
 * Initialises the CHIP/Matter stack and drives the lighting state machine.
 * Hardware LED is currently a stub — wire to a real GPIO
 * using Zephyr's gpio_pin_set() when the EVB LED pin is known.
 */

#include "AppTask.h"
#include "AppEvent.h"

#include <app-common/zap-generated/attributes/Accessors.h>
#include <app/clusters/identify-server/identify-server.h>
#include <app/clusters/on-off-server/on-off-server.h>
#include <app/server/Server.h>
#include <credentials/DeviceAttestationCredsProvider.h>
#include <credentials/examples/DeviceAttestationCredsExample.h>
#include <platform/Zephyr/DeviceInstanceInfoProviderImpl.h>
#include <DeviceInfoProviderImpl.h>
#include <data-model-providers/codegen/Instance.h>
#include <lib/core/ErrorStr.h>
#include <lib/support/CHIPMem.h>
#include <lib/support/CodeUtils.h>
#include <platform/CHIPDeviceLayer.h>
#include <setup_payload/OnboardingCodesUtil.h>

#ifdef CONFIG_NET_L2_OPENTHREAD
#include <platform/OpenThread/GenericNetworkCommissioningThreadDriver.h>
#include <app/clusters/network-commissioning/network-commissioning.h>
#include <app/clusters/network-commissioning/CodegenInstance.h>
#endif

#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>

extern "C" {
#include "hosal_rf.h"
#include "hosal_lpm.h"
/* Include low-level SDK headers before HOSAL wrappers so that the underlying
 * enum/constant names (GPIO_PIN_INT_BOTH_EDGE, PULLUP_100K, etc.) that the
 * HOSAL macros expand to are already declared when the macros are used. */
#include "gpio.h"          /* gpio_pin_int_mode_t, GPIO_PIN_INT_BOTH_EDGE */
#include "sysctrl.h"       /* PULLUP_100K */
#include "hosal_gpio.h"    /* hosal_gpio_cfg_input, hosal_gpio_pin_get, … */
#include "hosal_sysctrl.h" /* hosal_pin_set_pullopt, HOSAL_PULL_UP_100K */
#include "mcu.h"           /* Gpio_IRQn, NVIC_SetPriority, NVIC_EnableIRQ,
                              DEBOUNCE_SLOWCLOCKS_1024 */
/* RT583 SDK combined GPIO ISR (dispatches to per-pin callbacks) */
extern void gpio_handler(void);
extern bool hci_rt58x_rf_already_init;
int lmac15p4_init(uint8_t modem, uint8_t band_type);
void lmac15p4_phy_pib_set(uint16_t, uint8_t, uint8_t, uint16_t);
void lmac15p4_mac_pib_set(uint32_t, uint32_t, uint8_t, uint8_t, uint32_t, uint8_t, uint8_t);
int hosal_rf_write_command(uint8_t *, uint32_t);
}

/* Zephyr ISR wrapper for the RT583 GPIO interrupt (Gpio_IRQn = 0).
 * IRQ_CONNECT requires a void (*)(const void *) signature; gpio_handler()
 * takes void, so we wrap it.  This must live at file scope so the linker
 * section entry generated by IRQ_CONNECT persists across Init(). */
static void gpio_zephyr_isr(const void * /*arg*/) { gpio_handler(); }

/* Hardware crypto self-test (CryptoSelfTest.cpp) */
void crypto_selftest(void);

extern "C" {
void ot_radioInit(void);
void ot_alarmInit(void);
void ot_entropy_init(void);
void ot_set_instance(struct otInstance *inst);
}

#ifdef CONFIG_NET_L2_OPENTHREAD
#include <zephyr/net/openthread.h>  /* openthread_init(), openthread_get_default_instance() */
#include <openthread/ip6.h>          /* otIp6SetEnabled */
#include <openthread/thread.h>       /* OT_DEVICE_ROLE_LEADER */
#include <openthread/thread_ftd.h>   /* otThreadSetRouterEligible (FTD-only API) */
#include <openthread/dataset.h>      /* otDatasetGetActive, otOperationalDataset */
#include <zephyr/net/net_if.h>       /* net_if_up, net_if_get_default */
#endif
#ifdef CONFIG_OPENTHREAD_SRP_SERVER
#include <openthread/srp_server.h>   /* otSrpServerSetEnabled */
#endif

#if CHIP_SYSTEM_CONFIG_USE_OPENTHREAD_ENDPOINT
#include <inet/EndPointStateOpenThread.h>
#include <platform/Zephyr/ThreadStackManagerImpl.h>  /* ThreadStackMgrImpl().OTInstance() */
#endif

LOG_MODULE_DECLARE(app, CONFIG_CHIP_APP_LOG_LEVEL);

using namespace ::chip;
using namespace ::chip::app;
using namespace ::chip::Credentials;
using namespace ::chip::DeviceLayer;

namespace {

constexpr EndpointId kLightEndpointId          = 1;
constexpr int        kAppEventQueueSize         = 10;
constexpr uint32_t   kFactoryResetTriggerTimeMs = 6000; /* hold GPIO0 6 s to factory reset */
constexpr uint8_t    kButtonFactoryReset        = 0;    /* GPIO pin for factory reset */
constexpr uint8_t    kButtonLightToggle         = 1;    /* GPIO pin for light toggle */

K_MSGQ_DEFINE(sAppEventQueue, sizeof(AppEvent), kAppEventQueueSize, alignof(AppEvent));

Identify sIdentify = {
    kLightEndpointId,
    AppTask::IdentifyStartHandler,
    AppTask::IdentifyStopHandler,
    Clusters::Identify::IdentifyTypeEnum::kVisibleIndicator,
};

#ifdef CONFIG_NET_L2_OPENTHREAD
app::Clusters::NetworkCommissioning::InstanceAndDriver<NetworkCommissioning::GenericThreadDriver>
    sThreadNetworkDriver(0 /* endpoint */);
#endif

} /* namespace */

/* File-scope pointer to the serverParams so ServerInitWork can access it. */
chip::CommonCaseDeviceServerInitParams * gServerInitParams = nullptr;

/* ── LED simulation (replace with real GPIO when EVB LED pin is known) ─────── */

void AppTask::SetLed(bool on, uint8_t level)
{
    /* TODO: wire to GPIO
     * const struct device *led = DEVICE_DT_GET(DT_ALIAS(led0));
     * gpio_pin_set(led, PIN, on ? 1 : 0);
     */
    ARG_UNUSED(on);
    ARG_UNUSED(level);
}

/* ── Public API ─────────────────────────────────────────────────────────────── */

void AppTask::SetLightOn(bool on)
{
    mLightOn = on;
    SetLed(mLightOn, mLightLevel);
}

void AppTask::SetLightLevel(uint8_t level)
{
    mLightLevel = level;
    if (mLightOn) {
        SetLed(true, mLightLevel);
    }
}

void AppTask::UpdateClusterState()
{
    using namespace chip::app::Clusters;

    Protocols::InteractionModel::Status status;

    status = OnOff::Attributes::OnOff::Set(kLightEndpointId, mLightOn);
    if (status != Protocols::InteractionModel::Status::Success) {
        LOG_ERR("UpdateClusterState: OnOff write failed (%u)",
                chip::to_underlying(status));
    }

    status = LevelControl::Attributes::CurrentLevel::Set(kLightEndpointId, mLightLevel);
    if (status != Protocols::InteractionModel::Status::Success) {
        LOG_ERR("UpdateClusterState: Level write failed (%u)",
                chip::to_underlying(status));
    }
}

/* ── Identify cluster callbacks ─────────────────────────────────────────────── */

void AppTask::IdentifyStartHandler(Identify *)
{
}

void AppTask::IdentifyStopHandler(Identify *)
{
    AppTask::Instance().SetLed(AppTask::Instance().IsLightOn(),
                               AppTask::Instance().GetLightLevel());
}

/* ── CHIP device event handler ──────────────────────────────────────────────── */

void AppTask::ChipEventHandler(const ChipDeviceEvent * event, intptr_t /* arg */)
{
    switch (event->Type) {
    case DeviceEventType::kCHIPoBLEAdvertisingChange:
        LOG_INF("BLE advertising: %s",
                event->CHIPoBLEAdvertisingChange.Result == kActivity_Started
                    ? "started" : "stopped");
        break;
    case DeviceEventType::kThreadConnectivityChange:
        LOG_INF("Thread connectivity: %s",
                event->ThreadConnectivityChange.Result == kConnectivity_Established
                    ? "established" : "lost");
        break;
    case DeviceEventType::kThreadStateChange:
        if (event->ThreadStateChange.RoleChanged) {
#ifdef CONFIG_NET_L2_OPENTHREAD
            otInstance * inst = openthread_get_default_instance();
            otDeviceRole role = inst ? otThreadGetDeviceRole(inst) : OT_DEVICE_ROLE_DISABLED;
            static const char * const kRoleStr[] = {
                "Disabled", "Detached", "Child", "Router", "Leader"
            };
            const char *roleStr = (role < (int)ARRAY_SIZE(kRoleStr)) ? kRoleStr[role] : "Unknown";
            LOG_INF("[OT] Role changed: %s", roleStr);

            /* Print active dataset so it can be compared with OTBR
             * (sudo ot-ctl channel / panid / networkkey). */
            if (inst) {
                otOperationalDataset ds;
                openthread_mutex_lock();
                otError dsErr = otDatasetGetActive(inst, &ds);
                openthread_mutex_unlock();
                if (dsErr == OT_ERROR_NONE) {
                    if (ds.mComponents.mIsChannelPresent) {
                        LOG_DBG("[OT] dataset channel=%u", ds.mChannel);
                    }
                    if (ds.mComponents.mIsPanIdPresent) {
                        LOG_DBG("[OT] dataset panid=0x%04x", ds.mPanId);
                    }
                    if (ds.mComponents.mIsNetworkKeyPresent) {
                        LOG_HEXDUMP_DBG(ds.mNetworkKey.m8, OT_NETWORK_KEY_SIZE,
                                        "[OT] dataset networkkey");
                    }
                }
            }

            /*
             * ── Commissioning-phase router eligibility guard ──────────────────
             *
             * Problem: When the Matter commissioner provisions a Thread dataset
             * via BLE, RT583 becomes Detached and sends MLE Parent Requests.
             * If OTBR doesn't respond within ~7 s (wrong key, busy, etc.),
             * RT583 forms its own partition (→ Leader).  The commissioner then
             * cannot reach RT583 via CASE over Thread (needs OTBR as border
             * router) → fail-safe timer expires → commissioning fails.
             *
             * Fix: While the fail-safe is armed (commissioning in progress),
             * disable router eligibility when the device becomes Detached.
             * An FTD with router eligibility off keeps sending MLE Parent
             * Requests indefinitely and never forms a standalone partition.
             * Once the device joins OTBR's network (→ Child), re-enable
             * eligibility so it can promote to Router normally.
             *
             * After commissioning (fail-safe disarmed), the guard is inactive:
             * if OTBR is absent on reboot the device becomes Leader as normal
             * (standalone SRP server mode).
             */
            if (inst) {
                bool failSafeArmed =
                    chip::Server::GetInstance().GetFailSafeContext().IsFailSafeArmed();

                if (role == OT_DEVICE_ROLE_DETACHED && failSafeArmed) {
                    openthread_mutex_lock();
                    otThreadSetRouterEligible(inst, false);
                    openthread_mutex_unlock();
                    LOG_INF("[OT] Commissioning: router eligibility off");
                } else if (role == OT_DEVICE_ROLE_CHILD || role == OT_DEVICE_ROLE_ROUTER) {
                    openthread_mutex_lock();
                    otThreadSetRouterEligible(inst, true);
                    openthread_mutex_unlock();
                    LOG_INF("[OT] Joined: router eligibility on");
                }
            }

#ifdef CONFIG_OPENTHREAD_SRP_SERVER
            /* Enable the built-in SRP server when this device is the Thread
             * Leader (standalone — no Border Router).  The SRP server
             * publishes its anycast address via NETDATA_PUBLISHER, the SRP
             * client auto-starts and registers services, and the Matter DNS-SD
             * init callback fires → mState=kInitialized → advertising works.
             * When an OTBR is present the device is not Leader; the SRP server
             * stays off and the OTBR provides the SRP server instead. */
            if (inst) {
                openthread_mutex_lock();
                otSrpServerSetEnabled(inst, role == OT_DEVICE_ROLE_LEADER);
                openthread_mutex_unlock();
            }
#endif
#endif
        }
        break;
    case DeviceEventType::kInternetConnectivityChange:
        LOG_INF("Internet connectivity: %s",
                event->InternetConnectivityChange.IPv6 == kConnectivity_Established
                    ? "established" : "lost");
        break;
    case DeviceEventType::kCommissioningComplete:
        LOG_INF("Commissioning complete");
        break;
    default:
        break;
    }
}

/* ── Event dispatch ─────────────────────────────────────────────────────────── */

void AppTask::PostEvent(const AppEvent & event)
{
    if (k_msgq_put(&sAppEventQueue, &event, K_NO_WAIT) != 0) {
        LOG_ERR("PostEvent: queue full");
    }
}

void AppTask::DispatchEvent(const AppEvent & event)
{
    if (event.Handler) {
        event.Handler(event);
    }
}

void AppTask::LightingActionEventHandler(const AppEvent & event)
{
    AppTask & task = AppTask::Instance();

    switch (event.LightingEvent.Action) {
    case LightingAction::On:
        task.SetLightOn(true);
        break;
    case LightingAction::Off:
        task.SetLightOn(false);
        break;
    case LightingAction::Toggle:
        task.SetLightOn(!task.IsLightOn());
        break;
    case LightingAction::Level:
        task.SetLightLevel(event.LightingEvent.Level);
        break;
    }
}

/* ── Button factory reset ───────────────────────────────────────────────────── */

static void DoFactoryReset(intptr_t /* arg */)
{
    LOG_INF("[BTN] Executing factory reset");

    auto & server     = chip::Server::GetInstance();
    auto & fabricTable = server.GetFabricTable();
    auto & sessionMgr  = server.GetSecureSessionManager();

    /* Expire all CASE sessions, then delete all fabrics */
    for (const auto & fabricInfo : fabricTable) {
        sessionMgr.ExpireAllSessionsForFabric(fabricInfo.GetFabricIndex());
    }
    fabricTable.DeleteAllFabrics();

#ifdef CONFIG_NET_L2_OPENTHREAD
    /* Clear SRP host/services before leaving Thread network */
    if (chip::DeviceLayer::ThreadStackMgr().IsThreadAttached()) {
        chip::DeviceLayer::ThreadStackMgr().ClearAllSrpHostAndServices();
    }
    chip::DeviceLayer::ConnectivityMgr().ErasePersistentInfo();
#endif

    server.ScheduleFactoryReset();
}

/* Called by CHIP SystemLayer timer when GPIO0 has been held for 6 s.
 * Runs on the CHIP event loop thread (via TimerEventHandler → PostEvent →
 * DispatchEvent).  Safe to call PlatformMgr().ScheduleWork() from here. */
void AppTask::FunctionTimerEventHandler(const AppEvent & event)
{
    if (event.Type != AppEventType::Timer) {
        return;
    }
    AppTask & task = AppTask::Instance();
    if (task.mFunctionTimerActive && task.mFunction == FunctionEvent::FactoryReset) {
        task.mFunction            = FunctionEvent::NoneSelected;
        task.mFunctionTimerActive = false;
        LOG_INF("[BTN] Factory reset triggered (6 s hold)");
        (void) chip::DeviceLayer::PlatformMgr().ScheduleWork(DoFactoryReset, 0);
    }
}

/* Runs on the CHIP SystemLayer timer thread → posts a Timer event to the app
 * queue so FunctionTimerEventHandler runs in the app event loop. */
void AppTask::TimerEventHandler(chip::System::Layer * /* layer */, void * appState)
{
    AppEvent event;
    event.Type                = AppEventType::Timer;
    event.TimerEvent.Context  = appState;
    event.Handler             = FunctionTimerEventHandler;
    AppTask::PostEvent(event);
}

void AppTask::StartTimer(uint32_t timeoutMs)
{
    CHIP_ERROR err;
    chip::DeviceLayer::PlatformMgr().LockChipStack();
    err = chip::DeviceLayer::SystemLayer().StartTimer(
        chip::System::Clock::Milliseconds32(timeoutMs), TimerEventHandler, this);
    chip::DeviceLayer::PlatformMgr().UnlockChipStack();
    if (err != CHIP_NO_ERROR) {
        LOG_ERR("StartTimer failed: %" CHIP_ERROR_FORMAT, err.Format());
        return;
    }
    mFunctionTimerActive = true;
}

void AppTask::CancelTimer()
{
    chip::DeviceLayer::PlatformMgr().LockChipStack();
    chip::DeviceLayer::SystemLayer().CancelTimer(TimerEventHandler, this);
    chip::DeviceLayer::PlatformMgr().UnlockChipStack();
    mFunctionTimerActive = false;
}

/* Handles button press/release events dispatched from the app event loop.
 * GPIO0 = factory reset: press starts 6 s timer, release before 6 s cancels.
 * GPIO1 = light toggle: toggle on release. */
void AppTask::FunctionHandler(const AppEvent & event)
{
    AppTask & task = AppTask::Instance();

    if (event.ButtonEvent.ButtonIdx == kButtonFactoryReset) {
        if (event.ButtonEvent.Pressed) {
            if (!task.mFunctionTimerActive && task.mFunction == FunctionEvent::NoneSelected) {
                LOG_INF("[BTN] GPIO0 pressed, hold 6s for reset");
                task.mFunction = FunctionEvent::FactoryReset;
                task.StartTimer(kFactoryResetTriggerTimeMs);
            }
        } else {
            if (task.mFunctionTimerActive && task.mFunction == FunctionEvent::FactoryReset) {
                task.CancelTimer();
                task.mFunction = FunctionEvent::NoneSelected;
                LOG_INF("[BTN] GPIO0 released, reset cancelled");
            }
        }
    } else if (event.ButtonEvent.ButtonIdx == kButtonLightToggle) {
        if (!event.ButtonEvent.Pressed) {
            /* Toggle light on release */
            AppEvent lightEvent;
            lightEvent.Type                  = AppEventType::Lighting;
            lightEvent.LightingEvent.Action  = LightingAction::Toggle;
            lightEvent.LightingEvent.Level   = 0;
            lightEvent.Handler               = LightingActionEventHandler;
            AppTask::PostEvent(lightEvent);
        }
    }
}

/* GPIO ISR callback — called from hardware ISR context.
 * Must NOT call printk or LOG_* (spinlock deadlock on single-core Cortex-M3).
 * Uses k_msgq_put with K_NO_WAIT which is ISR-safe in Zephyr. */
void AppTask::ButtonEventHandler(uint32_t pin, void * /* isr_param */)
{
    uint32_t pin_status = 1; /* default: not pressed */
    hosal_gpio_pin_get(pin, &pin_status);
    /* Active-low with 100k pull-up: 0 = pressed, 1 = released */

    AppEvent event                  = {};
    event.Type                      = AppEventType::Button;
    event.ButtonEvent.ButtonIdx     = static_cast<uint8_t>(pin);
    event.ButtonEvent.Pressed       = (pin_status == 0);
    event.Handler                   = FunctionHandler;

    k_msgq_put(&sAppEventQueue, &event, K_NO_WAIT);
}

/* ── Initialisation ─────────────────────────────────────────────────────────── */

CHIP_ERROR AppTask::Init()
{
    CHIP_ERROR err;
    uint32_t t0, phase_ms;

    /* ── Firmware version marker ────────────────────────────────────────────
     * Confirms new firmware is running and AppTask::Init() is entered.
     * If this line is absent from the log the object file was not rebuilt. */
    printk("[BOOT] AppTask::Init (build " __DATE__ " " __TIME__ ")\n");
    t0 = k_uptime_get_32();

    /* Hardware crypto self-test — must run before hosal_rf_init() so the
     * shared AES/ECC accelerator is idle and lmac15p4 has not started. */
    crypto_selftest();
    phase_ms = k_uptime_get_32() - t0;
    printk("[BOOT] crypto_selftest: %u ms\n", phase_ms);

    /* Initialize RF MCU in multi-protocol mode (BLE + 802.15.4/Thread).
     * Must be called once before InitChipStack() triggers either BLE or OT
     * radio init.  The BLE HCI driver (hci_rt58x_open) and OT radio layer
     * both require an initialized RF MCU; MULTI_PROTOCOL loads firmware that
     * supports both simultaneously. */
    t0 = k_uptime_get_32();
    hosal_lpm_init();
    hosal_lpm_ioctrl(HOSAL_LPM_SET_POWER_LEVEL, HOSAL_LOW_POWER_LEVEL_SLEEP0);
    hosal_rf_init(HOSAL_RF_MODE_MULTI_PROTOCOL);
    k_sleep(K_MSEC(50));

    /* Match Rafael official Matter SDK init sequence (BLEManagerImpl.cpp):
     * hosal_rf_init → lmac15p4_init → phy_pib_set → mac_pib_set → ble_init
     * lmac15p4_init + PIB setup must happen HERE, before BLE and OT start.
     * ot_radioInit() below will only set callbacks (lmac15p4_cb_set), NOT
     * call lmac15p4_init again. */
    lmac15p4_init(2 /*LMAC15P4_2P4G_OQPSK*/, 0);
    lmac15p4_phy_pib_set(128, 1, 85, 128);
    lmac15p4_mac_pib_set(320, 544, 8, 10, 16896, 4, 5);

    /* Send RUCI_INITIATE_BLE right after lmac15p4_init — matching Rafael
     * official SDK timing (BLEManagerImpl: rf_init → lmac15p4_init → PIB →
     * ble_init which sends INITIATE_BLE internally).  This must happen here
     * and NOT later in hci_rt58x_setup(), because late INITIATE_BLE causes
     * the RF MCU scheduler to stop polling the 15.4 TX queue. */
    {
        uint8_t ruci_ble_init[] = { 0x10, 0x01, 0x00 }; /* INITIATE_BLE */
        hosal_rf_write_command(ruci_ble_init, sizeof(ruci_ble_init));
        k_sleep(K_MSEC(20));
        printk("[BOOT] RUCI_INITIATE_BLE sent (early, matching Rafael SDK)\n");
    }

    hci_rt58x_rf_already_init = true;  /* tell BLE HCI driver to skip re-init */
    phase_ms = k_uptime_get_32() - t0;
    printk("[BOOT] RF init + settle: %u ms\n", phase_ms);

    /* Initialise lmac15p4 radio layer for OpenThread (sets up RUCI callbacks,
     * channel, and MAC address from OTP/flash).  Must be called after
     * hosal_rf_init() so the RF MCU RUCI interface is ready. */
    t0 = k_uptime_get_32();
    ot_radioInit();
    ot_alarmInit();
    ot_entropy_init();
    phase_ms = k_uptime_get_32() - t0;
    printk("[BOOT] OT radio+alarm+entropy: %u ms\n", phase_ms);

#ifdef CONFIG_NET_L2_OPENTHREAD
    /* Explicitly initialise the OT instance on this thread (8 KB stack).
     * openthread_init() calls otInstanceInitSingle() which needs ~4 KB of
     * stack — far more than the 2 KB main thread used during POST_KERNEL
     * device init.  After this call openthread_get_default_instance() returns
     * a valid pointer and InitThreadStack() no longer asserts. */
    t0 = k_uptime_get_32();
    {
        int ot_err = openthread_init();
        if (ot_err != 0) {
            LOG_ERR("openthread_init failed: %d", ot_err);
        }
    }
    /* Sync our ot_instance accessor (used by ot_alarmTask / ot_radioTask)
     * with Zephyr's openthread_instance set by openthread_init(). */
    ot_set_instance(openthread_get_default_instance());
    phase_ms = k_uptime_get_32() - t0;
    printk("[BOOT] openthread_init: %u ms\n", phase_ms);
#endif

    /* Initialise CHIP memory allocator */
    err = chip::Platform::MemoryInit();
    VerifyOrReturnError(err == CHIP_NO_ERROR, err,
                        LOG_ERR("MemoryInit failed: %" CHIP_ERROR_FORMAT, err.Format()));

    /* Initialise CHIP device layer (BLE + OpenThread) */
    t0 = k_uptime_get_32();
    err = PlatformMgr().InitChipStack();
    phase_ms = k_uptime_get_32() - t0;
    printk("[BOOT] InitChipStack: %u ms\n", phase_ms);
    VerifyOrReturnError(err == CHIP_NO_ERROR, err,
                        LOG_ERR("InitChipStack failed: %" CHIP_ERROR_FORMAT, err.Format()));

    /* Register device event handler */
    err = PlatformMgr().AddEventHandler(ChipEventHandler, 0);
    VerifyOrReturnError(err == CHIP_NO_ERROR, err,
                        LOG_ERR("AddEventHandler failed: %" CHIP_ERROR_FORMAT, err.Format()));

#ifdef CONFIG_NET_L2_OPENTHREAD
    err = ThreadStackMgr().InitThreadStack();
    VerifyOrReturnError(err == CHIP_NO_ERROR, err,
                        LOG_ERR("InitThreadStack failed: %" CHIP_ERROR_FORMAT, err.Format()));

    err = ConnectivityMgr().SetThreadDeviceType(
        ConnectivityManager::kThreadDeviceType_Router);
    VerifyOrReturnError(err == CHIP_NO_ERROR, err,
                        LOG_ERR("SetThreadDeviceType failed: %" CHIP_ERROR_FORMAT, err.Format()));

    err = sThreadNetworkDriver.Init();
    VerifyOrReturnError(err == CHIP_NO_ERROR, err,
                        LOG_ERR("ThreadNetworkDriver Init failed: %" CHIP_ERROR_FORMAT, err.Format()));

    /* Enable OT IPv6 so that OT UDP endpoints (mDNS, CASE) work.
     * With CONFIG_CHIP_USE_OT_ENDPOINT=y, Matter uses otUdp* directly —
     * no POSIX socket bind() needed, so the net_if_up() workaround is gone.
     * otIp6SetEnabled must still be called here because InitThreadStack()
     * only enables IPv6 under THREAD_AUTOSTART when the dataset is already
     * commissioned, which is not the case on first boot. */
    openthread_mutex_lock();
    otIp6SetEnabled(openthread_get_default_instance(), true);
    openthread_mutex_unlock();
#endif

    /* Initialise Matter server (GATT, mDNS, session management) */
    static chip::CommonCaseDeviceServerInitParams sServerInitParams;
    gServerInitParams = &sServerInitParams;
    err = sServerInitParams.InitializeStaticResourcesBeforeServerInit();
    VerifyOrReturnError(err == CHIP_NO_ERROR, err,
                        LOG_ERR("ServerInitParams failed: %" CHIP_ERROR_FORMAT, err.Format()));

    /* Use example (test) DAC provider — replace with factory data for production */
    SetDeviceAttestationCredentialsProvider(
        Examples::GetExampleDACProvider());

    /* DeviceInstanceInfoProvider — required by BasicInformation cluster init.
     * Must be set before Server::Init which triggers SetDataModelProvider. */
    static DeviceLayer::DeviceInstanceInfoProviderImpl sDeviceInstanceInfoProvider(
        DeviceLayer::ConfigurationManagerImpl::GetDefaultInstance());
    DeviceLayer::SetDeviceInstanceInfoProvider(&sDeviceInstanceInfoProvider);

    /* DeviceInfoProvider — required by UserLabel cluster init. */
    static DeviceLayer::DeviceInfoProviderImpl sDeviceInfoProvider;
    sDeviceInfoProvider.SetStorageDelegate(sServerInitParams.persistentStorageDelegate);
    DeviceLayer::SetDeviceInfoProvider(&sDeviceInfoProvider);

    /* Data model provider — required since connectedhomeip removed the default. */
    sServerInitParams.dataModelProvider =
        chip::app::CodegenDataModelProviderInstance(sServerInitParams.persistentStorageDelegate);

    /* ── Button GPIO init ───────────────────────────────────────────────────────
     * GPIO0 = factory reset (hold 6 s), GPIO1 = light toggle.
     * Active-low with 100 kΩ pull-up.  Both edges so we can detect press and
     * release.  Debounce = 1024 slow clocks (~31 ms at 32 kHz slow clock).
     *
     * Gpio_IRQn = 0 on RT583.  IRQ_CONNECT is required (not just NVIC_EnableIRQ)
     * so that Zephyr's ISR dispatch table entry 0 is populated with our wrapper.
     * Without it z_irq_spurious fires on the first GPIO edge and causes a fatal
     * "Unhandled interrupt" crash (seen on first two boots before buttons settle). */
    {
        hosal_gpio_input_config_t pin_cfg;
        pin_cfg.param        = nullptr;
        pin_cfg.pin_int_mode = HOSAL_GPIO_PIN_INT_BOTH_EDGE;
        pin_cfg.usr_cb       = reinterpret_cast<void *>(ButtonEventHandler);

        hosal_gpio_set_debounce_time(DEBOUNCE_SLOWCLOCKS_1024);

        /* Register gpio_zephyr_isr in Zephyr's dispatch table for IRQ 0 and
         * enable the NVIC line.  IRQ_CONNECT sets the priority internally. */
        IRQ_CONNECT(0, 1, gpio_zephyr_isr, NULL, 0);
        irq_enable(0);

        for (uint8_t i = kButtonFactoryReset; i <= kButtonLightToggle; i++) {
            hosal_pin_set_pullopt(i, HOSAL_PULL_UP_100K);
            hosal_gpio_cfg_input(i, pin_cfg);
            hosal_gpio_debounce_enable(i);
            hosal_gpio_int_enable(i);
        }
        LOG_INF("[BTN] GPIO%u=reset GPIO%u=toggle",
                kButtonFactoryReset, kButtonLightToggle);
    }

    return CHIP_NO_ERROR;
}

/* Called from the CHIP event loop thread via ScheduleWork — holds the
 * stack lock and can safely post platform events. */
static void ServerInitWork(intptr_t arg)
{
    auto * serverParams = reinterpret_cast<chip::CommonCaseDeviceServerInitParams *>(arg);

#if CHIP_SYSTEM_CONFIG_USE_OPENTHREAD_ENDPOINT
    /* Wire OpenThread's native UDP stack into Matter's inet layer.
     * With CONFIG_CHIP_USE_OT_ENDPOINT=y, all UDP endpoints (CASE, mDNS)
     * use otUdp* directly — no POSIX socket bind() required.  This fixes
     * the "Failed to advertise commissionable node: 3" (CHIP_ERROR_INCORRECT_STATE)
     * that occurred because Advertiser_ImplMinimalMdns::Init() couldn't bind
     * a POSIX socket (EADDRNOTAVAIL: no Zephyr net_if for the vendored lmac15p4
     * Thread radio).  With a valid OT instance here, Init() uses otUdpBind()
     * on the Thread interface and succeeds. */
    chip::Inet::EndPointStateOpenThread::OpenThreadEndpointInitParam nativeParams;
    nativeParams.lockCb   = []() { chip::DeviceLayer::ThreadStackMgr().LockThreadStack(); };
    nativeParams.unlockCb = []() { chip::DeviceLayer::ThreadStackMgr().UnlockThreadStack(); };
    nativeParams.openThreadInstancePtr = chip::DeviceLayer::ThreadStackMgrImpl().OTInstance();
    serverParams->endpointNativeParams = static_cast<void *>(&nativeParams);
#endif

    uint32_t t0 = k_uptime_get_32();
    CHIP_ERROR err = chip::Server::GetInstance().Init(*serverParams);
    LOG_INF("[APP] Server::Init took %u ms", k_uptime_get_32() - t0);
    if (err != CHIP_NO_ERROR) {
        LOG_ERR("Server::Init failed: %" CHIP_ERROR_FORMAT, err.Format());
        return;
    }

#if defined(MATTER_FACTORY_RESET_ON_BOOT)
    /* One-shot factory reset: clears all Matter KVS data + OT NVM, then reboots.
     * Build with -DMATTER_FACTORY_RESET_ON_BOOT=1 (CMake, not Kconfig) to wipe
     * the device once; rebuild without it for normal operation. */
    LOG_INF("MATTER_FACTORY_RESET_ON_BOOT — initiating factory reset");
    chip::Server::GetInstance().ScheduleFactoryReset();
    return;
#endif

    /* Set initial light state */
    AppTask & task = AppTask::Instance();
    task.SetLightOn(task.IsLightOn());
    task.UpdateClusterState();

    /* Print commissioning QR code URL and manual pairing code */
    PrintOnboardingCodes(chip::RendezvousInformationFlags(
        chip::RendezvousInformationFlag::kBLE));
}

/* ── Main event loop ────────────────────────────────────────────────────────── */

CHIP_ERROR AppTask::StartApp()
{
    CHIP_ERROR err = Init();
    if (err != CHIP_NO_ERROR) {
        LOG_ERR("AppTask::Init() failed: %" CHIP_ERROR_FORMAT, err.Format());
        return err;
    }

    /* Start CHIP device layer event loop BEFORE Server::Init.
     * Server::Init → emberAfInit → cluster callbacks may call PostEventOrDie
     * which requires the event loop to be running. */
    err = PlatformMgr().StartEventLoopTask();
    VerifyOrReturnError(err == CHIP_NO_ERROR, err,
                        LOG_ERR("StartEventLoopTask failed: %" CHIP_ERROR_FORMAT, err.Format()));

    /* Schedule Server::Init on the CHIP event loop thread so it holds the
     * stack lock and can dispatch platform events.  The serverParams static
     * in Init() outlives this call. */
    {
        /* Get pointer to the static serverParams in Init() — it's the only
         * CommonCaseDeviceServerInitParams we created. */
        extern chip::CommonCaseDeviceServerInitParams * gServerInitParams;
        err = PlatformMgr().ScheduleWork(ServerInitWork,
                                         reinterpret_cast<intptr_t>(gServerInitParams));
        VerifyOrReturnError(err == CHIP_NO_ERROR, err,
                            LOG_ERR("ScheduleWork failed: %" CHIP_ERROR_FORMAT, err.Format()));
    }

#ifdef CONFIG_NET_L2_OPENTHREAD
    err = ThreadStackMgr().StartThreadTask();
    VerifyOrReturnError(err == CHIP_NO_ERROR, err,
                        LOG_ERR("StartThreadTask failed: %" CHIP_ERROR_FORMAT, err.Format()));
#endif

    /* Main app event loop */
    AppEvent event;
    while (true) {
        k_msgq_get(&sAppEventQueue, &event, K_FOREVER);
        DispatchEvent(event);
    }

    return CHIP_NO_ERROR;
}
