# RT583-EVB MCUboot extras.
# Upgrade mode + signature type are set in ../sysbuild.conf via SB_CONFIG_*.

CONFIG_FLASH_RT583=y
CONFIG_UART_RT583=y

CONFIG_SERIAL=y
CONFIG_UART_CONSOLE=y
CONFIG_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_MCUBOOT_LOG_LEVEL_INF=y
CONFIG_BOOT_BANNER=y

CONFIG_SIZE_OPTIMIZATIONS=y
CONFIG_MAIN_STACK_SIZE=2048

CONFIG_BUILD_OUTPUT_HEX=y
